name: mala-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - pip
  - numpy
  - scipy
  - optuna
  - pandas
  - ase
  - pytorch-cpu<=2.6.0
  - mpmath
  - tensorboard
  - scikit-spatial
  - mendeleev
  - sympy
  - requests
  - pip:
      - openpmd-api
